name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.18", "1.19", "1.20"]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download && go test -race ./sentrytracing

